services:
  aobaspace-api:
    build:
      context: ./aobaspace-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # Load environment variables from the .env file
    env_file:
      - ./aobaspace-api/.env # This loads all variables from the specified .env file
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - aobaspace-network
    command: ["./wait-for-it.sh", "postgres:5432", "--", "node", "dist/main"]

  aobaspace-web:
    build:
      context: ./aobaspace-web
      dockerfile: Dockerfile
    ports:
      - "3001:3000" # Frontend runs on port 3000 inside container, map to 3001 on host
    env_file:
      - ./aobaspace-web/.env
    depends_on:
      - aobaspace-api
    networks:
      - aobaspace-network

  postgres:
    image: postgres:14-alpine
    restart: always
    # Load environment variables from the .env file
    env_file:
      - ./aobaspace-api/.env # Postgres will now also read its env vars from this file
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aobaspace-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  aobaspace-network:
    driver: bridge

volumes:
  postgres_data: